[package]
name = "ff_wasm_unknown_unknown"
version = "0.12.2"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
    "Jack the Dev <joao@hackachain.io>"
]
description = "Independent adaptation of the open-sourced ff library that removes features incompatible with wasm32-unknown-unknown architecture"
readme = "README.md"
documentation = "https://docs.rs/ff/"
homepage = "https://github.com/zkcrypto/ff"
license = "MIT/Apache-2.0"
repository = "https://github.com/hideyour-cash/monorepo/packages/contract-libraries/ff_wasm_unknown_unknown"
edition = "2021"

[dependencies]
bitvec = { version = "1", default-features = false, optional = true }
byteorder = { version = "1", default-features = false, optional = true }
ff_derive_wasm_unknown_unknown = { version = "0.12.2", path = "ff_derive_wasm_unknown_unknown", optional = true }
subtle = { version = "2.2.1", default-features = false, features = ["i128"] }

[features]
default = ["bits", "std"]
alloc = []
bits = ["bitvec"]
derive = ["byteorder", "ff_derive_wasm_unknown_unknown"]
std = ["alloc"]
# with MSRV 1.60 this could be merged into bits with ff_derive?/bits
# see PR#72 for more information.
derive_bits = ["bits", "ff_derive_wasm_unknown_unknown/bits"]

[[test]]
name = "derive"
required-features = ["ff_derive_wasm_unknown_unknown"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
