[package]
name = "near-bigint"
version = "1.0.1"
authors = [
    "jack the dev <joao@hackachain.io>, hackerdocc <eduardo@hackachain.io>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/hideyour-cash/monorepo"
keywords = ["near_protocol", "big_integer"]
categories = [
    "cryptography::cryptocurrencies",
    "data-structures",
    "encoding",
    "mathematics",
]
description = "Big integer types compatible with NEAR Protocol state trie serialization and serde serialization"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.0.0" }
uint = "0.9.3"
paste = "1.0.9"

[dev-dependencies]
rstest = "0.14.0"

[profile.release]
codegen-units = 1
# s = optimize for binary size ("z" would additionally turn off loop vectorization)
opt-level = "z"
# link time optimization
lto = true
debug = false
panic = "abort"
overflow-checks = true
