[package]
name = "near_mimc"
version = "1.0.2"
authors = ["hackerdocc <eduardo@hackachain.io>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/hideyour-cash/monorepo/packages/contract-libraries/near_mimc"
keywords = ["near_protocol", "MiMC", "zero_knowledge", "cryptography"]
categories = [
    "cryptography",
    "cryptography::cryptocurrencies",
    "mathematics",
    "wasm",
]
description = "MiMC hash function implementation in wasm32_unknown_unknown architecture, compatible with NEAR Protocol Smart Contracts. Inspired by snarky.js' implementation."


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.0.0"
near-bigint = { path = "../near_bigint", version = "1.0.1" }
ff_wasm_unknown_unknown = { path = "../ff_wasm_unknown_unknown", features = [
    "derive",
], version = "0.12.2" }
