[package]
name = "ff_derive_wasm_unknown_unknown"
version = "0.12.2"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
    "Jack the Dev <joao@hackachain.io>"
]
description = "Independent adaptation of the open-sourced ff_derive library that removes features incompatible with wasm32-unknown-unknown architecture"
documentation = "https://docs.rs/ff-derive/"
homepage = "https://github.com/zkcrypto/ff"
license = "MIT/Apache-2.0"
repository = "https://github.com/hideyour-cash/monorepo/packages/contract-libraries/ff_wasm_unknown_unknown/ff_derive_wasm_unknown_unknown"
edition = "2021"

[features]
# enabled when generating bitvec code utilizing the version of ff's bitvec
bits = []

[lib]
proc-macro = true

[dependencies]
addchain = "0.2"
num-bigint = "0.3"
num-traits = "0.2"
num-integer = "0.1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
cfg-if = "1"

[badges]
maintenance = { status = "passively-maintained" }
